### ISSUE TITLE
Failed to connect to MQTT Broker

### ISSUE THREAD

**Issue by Yimi81** [tsinghua-fib-lab/agentsociety#11]
**版本 Version**
> 请首先尝试将AgentSociety升级到最新版
> Please first try to upgrade AgentSociety to the latest version
操作系统 OS: e.g. Ubuntu 22.04, macOS ARM
Python: 3.11
AgentSociety: 1.2.2

**描述错误 Describe the bug**

Failed to connect to MQTT Broker

docker-compose
```
services:
  mlflow:
    image: bitnami/mlflow:2.19.0
    container_name: mlflow
    restart: always
    entrypoint: ["bash", "/entrypoint.sh"]
    ports:
      - 59000:59000
    volumes:
      - /data/markyi/Projects/agentsociety/docker/mlflow/basic_auth.ini:/auth/basic_auth.ini
      - /data/markyi/Projects/agentsociety/docker/mlflow/entrypoint.sh:/entrypoint.sh
      - mlflow:/app
    environment:
      MLFLOW_AUTH_CONFIG_PATH: /auth/basic_auth.ini
      PG_DSN: postgresql://postgres:CHANGE_ME@localhost:5432/postgres
    depends_on:
      - postgresql

  postgresql:
    image: bitnami/postgresql:17
    container_name: postgresql
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/bitnami/postgresql
    environment:
      POSTGRESQL_PASSWORD: CHANGE_ME

  emqx:
    image: emqx:5.8.1
    container_name: emqx
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    ports:
      - 1883:1883 # TCP Listener for MQTT
      # - 8883:8883 # SSL Listener for MQTT
      # - 8083:8083 # WebSocket Listener for MQTT
      # - 8084:8084 # Secure WebSocket Listener for MQTT
      - 18083:18083 # Dashboard

volumes:
  mlflow:
  postgresql:
```
example_sim_config
```
llm_request:
  request_type: zhipuai
  api_key: 5125cc34ba4e # Please replace with the API key obtained from the LLM provider website.
  model: GLM-4-Flash # The name of the model to be used.

simulator_request:
  task_name: "citysim" # The name of the simulation task, affect the directory name for log output
  max_day: 1 # Defines the maximum number of days for the simulation.
  start_step: 0 # The initial step of the simulation in seconds.
  total_step: 86400 # Total steps in the simulation in seconds.
  log_dir: log # Directory where simulator logs will be stored.

mqtt:
  server: tcp://localhost:1883 # Specify the MQTT server address here.
  port: 1883 # Port number on which the MQTT service is running.
  username: admin # Username for MQTT server authentication.
  password: public # Password for MQTT server authentication.

map_request:
  file_path: data/beijing_map.pb # Path to the map file, reference to step1.

metric_request:
  mlflow: 
      username: postgres # Username for MLflow authentication.
      password: CHANGE_ME # Password for MLflow authentication.
      mlflow_uri: http://localhost:59000 # URI pointing to the MLflow tracking server.

pgsql:
  enabled: true # Whether PostgreSQL database integration is enabled.
  dsn: postgresql://postgres:CHANGE_ME@localhost:5432/postgres # Data source name for connecting to PostgreSQL.

avro:
  enabled: true # Whether Avro serialization is enabled.
  path: /data/markyi/Projects/agentsociety/data/avro_path # Directory path for storing cached data or serialized files.
```

**预期结果 Expected behavior**
> 给出对预期结果清晰简洁的描述
> A clear and concise description of what you expected to happen.

**截图 Screenshots**
docker
![Image](https://github.com/user-attachments/assets/b08b5c08-9c5e-4a2a-8fe0-b3fd322d741e)
bug

![Image](https://github.com/user-attachments/assets/3ab7d117-aa83-4dde-85d0-32f7703cffd9)

**Comment by Yimi81** [comment]
when i change sim_config.yaml to 
```
llm_request:
  request_type: zhipuai
  api_key: 5125cc34ba4e4fa98791429f54b81ca0.foAjiXheuZ1SLIbk # Please replace with the API key obtained from the LLM provider website.
  model: GLM-4-Flash # The name of the model to be used.

simulator_request:
  task_name: "citysim" # The name of the simulation task, affect the directory name for log output
  max_day: 1 # Defines the maximum number of days for the simulation.
  start_step: 0 # The initial step of the simulation in seconds.
  total_step: 86400 # Total steps in the simulation in seconds.
  log_dir: log # Directory where simulator logs will be stored.

mqtt:
  server: 127.0.0.1 # Specify the MQTT server address here.
  port: 1883 # Port number on which the MQTT service is running.
  username: admin # Username for MQTT server authentication.
  password: public # Password for MQTT server authentication.

map_request:
  file_path: data/beijing_map.pb # Path to the map file, reference to step1.

metric_request:
  mlflow: 
      username: postgres # Username for MLflow authentication.
      password: CHANGE_ME # Password for MLflow authentication.
      mlflow_uri: http://127.0.0.1:59000 # URI pointing to the MLflow tracking server.

pgsql:
  enabled: true # Whether PostgreSQL database integration is enabled.
  dsn: postgresql://postgres:CHANGE_ME@127.0.0.1:5432/postgres # Data source name for connecting to PostgreSQL.

avro:
  enabled: true # Whether Avro serialization is enabled.
  path: /data/markyi/Projects/agentsociety/data/avro_path # Directory path for storing cached data or serialized files.
```
 The error is as follows:

![Image](https://github.com/user-attachments/assets/7b631d82-a4d2-4bd0-8762-722970931013)
